### ISSUE TITLE
Unknown plugin "transform-object-rest-spread"

### ISSUE THREAD

**Issue by AMS777** [devotox/ember-paper-password#3]
Error on Ember.js 3.0 after installing ember-paper-password and launching the server:

> Build Error (Babel) in paper-password/components/paper-password.js
> 
> Unknown plugin "transform-object-rest-spread" specified in "base" at 0, attempted to resolve relative to "paper-password/components"

**Comment by devotox** [comment]
@AMS777 I am using ember 3.3 atm and do not see this issue
