### ISSUE TITLE
How can I use other than awesome icon?

### ISSUE THREAD

**Issue by wukongrita** [devotox/ember-paper-password#4]
@devotox as title... how? thank you...

**Comment by devotox** [comment]
You can overwrite the css and add what you want for these classes
```
		let open = 'fa-eye';
		let closed = 'fa-eye-slash';
		let classes = 'fa password-reveal';
```

Or extend the code and move these classes into a config that you can then pass some the classes you want in and have these set as defaults. If you do this and send a PR i will look at it ASAP
