### ISSUE TITLE
DEPRECATION: Importing password-strength deprecated. Use the passwordStrength service instead

### ISSUE THREAD

**Issue by wukongrita** [devotox/ember-paper-password#5]
I'm using Ember:
```
$ ember -v
ember-cli: 3.4.3
node: 8.9.4
os: darwin x64
```

having this issue:

```
DEPRECATION: Importing password-strength deprecated. Use the passwordStrength service instead
```

@devotox any update on this? thank you...

**Comment by devotox** [comment]
The problem using the non deprecated version was due to its asynchronous behaviour it caused flashes of the password strength on each keystroke rather than a smooth animation
